services:
  mongo:
    image: mongo:6-jammy
    restart: always

  estudiantes:
    build: .

  usuarios:
    build: ../practica3-rest
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      GRPC_ADDR: estudiantes:50051
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: practica3
    depends_on:
      - mongo
      - estudiantes