events { worker_connections 1024; }

http {
    # DNS interno de Docker para resolver las múltiples IPs de las réplicas
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location / {
            # Variable dinámica para forzar re-resolución DNS en cada petición
            set $backend "http://api:3000";
            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Healthcheck propio de Nginx
        location /salud-proxy {
            access_log off;
            return 200 "healthy\n";
        }
    }
}